[version]
current = "2.3.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "chore: bumped version to {new_version}"
tag_template = "{new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[file]]
src = "src/crcmod/_version.py"
version_template = "({major}, {minor}, {patch})"
search = "__version_tuple__ = {current_version}"

[[before_commit]]
name = "Run tests"
cmd = "tox && pre-commit run --all-files"
